--- !!dev.north.fortyone.gradle.intellij.run.generator.models.ApplicationRunConfig
# ------------------------------------------------------------------------------
# BESU - Dev Network
# ------------------------------------------------------------------------------
name: BESU | Dev > Run
filename: BESU__Dev__Run.xml
default: false
mainClassName: org.hyperledger.besu.Besu
module: besu-storage-ignite.plugin.main
envs:
  BESU_SYNC_MODE: FULL
  BESU_LOGGING: INFO
  BESU_P2P_ENABLED: 'false'
  BESU_RPC_WS_ENABLED: 'true'
  BESU_RPC_HTTP_ENABLED: 'true'
  BESU_RPC_HTTP_API: eth,net,web3,admin,debug
  BESU_NETWORK: DEV
  BESU_DATA_PATH: /opt/besu/dev
  BESU_MINER_ENABLED: 'true'
  BESU_MINER_COINBASE: '0xf17f52151EbEF6C7334FAD080c5704D77216b732'
  BESU_KEY_VALUE_STORAGE: ignite-storage
  BESU_PLUGIN_IGNITE_STORAGE_CONFIG_PATH: "../etc/ignite/config.xml"
--- !!dev.north.fortyone.gradle.intellij.run.generator.models.ApplicationRunConfig
# ------------------------------------------------------------------------------
# BESU - Ropsten Network
# ------------------------------------------------------------------------------
name: BESU | Ropsten > Run
filename: BESU__Ropsten__Run.xml
default: false
mainClassName: org.hyperledger.besu.Besu
module: besu-storage-ignite.plugin.main
envs:
  BESU_SYNC_MODE: FULL
  BESU_LOGGING: INFO
  BESU_P2P_ENABLED: 'true'
  BESU_RPC_WS_ENABLED: 'true'
  BESU_RPC_HTTP_ENABLED: 'true'
  BESU_RPC_HTTP_API: eth,net,web3,admin,debug
  BESU_NETWORK: ROPSTEN
  BESU_DATA_PATH: /opt/besu/ropsten
  BESU_KEY_VALUE_STORAGE: ignite-storage
  BESU_PLUGIN_IGNITE_STORAGE_CONFIG_PATH: "../etc/ignite/config.xml"
--- !!dev.north.fortyone.gradle.intellij.run.generator.models.ApplicationRunConfig
# ------------------------------------------------------------------------------
# BESU - Mainnet Network
# ------------------------------------------------------------------------------
name: BESU | Mainnet > Run
filename: BESU__Mainnet__Run.xml
default: false
mainClassName: org.hyperledger.besu.Besu
module: besu-storage-ignite.plugin.main
envs:
  BESU_SYNC_MODE: FULL
  BESU_LOGGING: INFO
  BESU_P2P_ENABLED: 'true'
  BESU_RPC_WS_ENABLED: 'true'
  BESU_RPC_HTTP_ENABLED: 'true'
  BESU_RPC_HTTP_API: eth,net,web3,admin,debug
  BESU_NETWORK: MAINNET
  BESU_DATA_PATH: /opt/besu/mainnet
  BESU_KEY_VALUE_STORAGE: ignite-storage
  BESU_PLUGIN_IGNITE_STORAGE_CONFIG_PATH: "../etc/ignite/config.xml"
